# This file was generated by GoReleaser. DO NOT EDIT.
cask "linctl" do
  version "0.24.0"

  on_macos do
    on_intel do
      sha256 "53d6244fd17fdb35772e834e408f006adf3e7f64cfa7786b8a3b925c19a53b05"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80d7571541af6d2aa04626a594c22c80fc00b33c80a8e9b9d791f82bf593f8e8"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1849e3b46d0e9ba2f889ad73aef620a20fe5a2e51ebc121622e3d524a67c9346"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f58b7c197fa11376a08409f7ae658a90a055bc9bacba5de02e5de8df12aa8f69"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "linctl"
  desc "Schema-aligned Linear CLI with fail-closed target-pinned writes."
  homepage "https://github.com/KyaniteHQ/linctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linctl"

  # No zap stanza required

end
