# This file was generated by GoReleaser. DO NOT EDIT.
cask "linctl" do
  version "0.25.0"

  on_macos do
    on_intel do
      sha256 "b49ab593f94650918d31abe35c8fd3f51b97eb8a2dd439c92f801b13b35df80b"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac90621cdea219f9229a58a92563d96a4d6b2c2a5d1cf916850ff51dbd28a972"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0d0c07b88348c394a25293f3fa9ed162df56132d1046c53018ed8677458f731a"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "835bd7fc475020aacd96612730154d9888e058f666c47f5cfe42298feb22c67b"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "linctl"
  desc "Schema-aligned Linear CLI with fail-closed target-pinned writes."
  homepage "https://github.com/KyaniteHQ/linctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linctl"

  # No zap stanza required

end
