# This file was generated by GoReleaser. DO NOT EDIT.
cask "linctl" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "b1a44bd91defb08ead39305a63675b08dff04d0bea90365842ed714b0ada3629"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "851f15a9bcc755c8af913c3fd5f1e35bf358d03de74d37586064d881149876f8"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d67683512e158920b8cd7ead6914c3424f417f198cc31e8b719a8f9118c47299"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "11e7bf5635f5ffd7ff359e02f67cabafa5ab244b1da0facff87cc5cd1b32149b"
      url "https://github.com/KyaniteHQ/linctl/releases/download/v#{version}/linctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "linctl"
  desc "Schema-aligned Linear CLI with fail-closed target-pinned writes."
  homepage "https://github.com/KyaniteHQ/linctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linctl"

  # No zap stanza required

end
